import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:uuid/uuid.dart';

import '../core/models/expense_model.dart';
import '../core/models/money_account.dart';
import 'user_data_service.dart';

class AccountService {
  AccountService._();

  static final FirebaseFirestore _firestore = FirebaseFirestore.instance;
  static final FirebaseAuth _auth = FirebaseAuth.instance;

  static CollectionReference<Map<String, dynamic>> _collection() {
    final uid = _auth.currentUser?.uid;
    if (uid == null || uid.isEmpty) {
      throw StateError('User must be logged in to use Firebase storage.');
    }
    return _firestore.collection('users').doc(uid).collection('accounts');
  }

  static Stream<List<MoneyAccount>> stream() {
    try {
      return _collection().snapshots().map(
        (snapshot) => snapshot.docs
            .map((doc) => MoneyAccount.fromMap(doc.id, doc.data()))
            .toList(),
      );
    } catch (_) {
      return Stream.value(const <MoneyAccount>[]);
    }
  }

  static Future<List<MoneyAccount>> getOnce() async {
    try {
      final snapshot = await _collection().get();
      return snapshot.docs
          .map((doc) => MoneyAccount.fromMap(doc.id, doc.data()))
          .toList();
    } catch (_) {
      return <MoneyAccount>[];
    }
  }

  static Future<MoneyAccount> create({
    required String name,
    required AccountKind kind,
    int openingBalancePaisa = 0,
  }) async {
    final account = MoneyAccount(
      id: const Uuid().v4(),
      name: name.trim(),
      kind: kind,
      openingBalancePaisa: openingBalancePaisa,
      createdAt: DateTime.now(),
    );
    await _collection().doc(account.id).set(account.toMap());
    return account;
  }

  static Future<void> save(MoneyAccount account) async {
    await _collection().doc(account.id).set(account.toMap());
  }

  /// Removes the account and unassigns anything that pointed at it.
  ///
  /// The transactions themselves are kept. They are real records of money
  /// moving, and deleting a wallet is not a statement that the spending never
  /// happened - it just stops being attributed anywhere.
  static Future<int> delete(String id) async {
    final transactions = await UserDataService.getTransactionsOnce();
    final affected = transactions.where((t) => t.accountId == id).toList();

    for (final transaction in affected) {
      await UserDataService.updateTransaction(
        transaction.id,
        ExpenseModel(
          id: transaction.id,
          title: transaction.title,
          amount: transaction.amount,
          category: transaction.category,
          date: transaction.date,
          isExpense: transaction.isExpense,
          recurringExpenseId: transaction.recurringExpenseId,
          isAutoGenerated: transaction.isAutoGenerated,
          isWindfall: transaction.isWindfall,
          accountId: null,
          transferGroupId: transaction.transferGroupId,
        ),
      );
    }

    await _collection().doc(id).delete();
    return affected.length;
  }

  /// Records money moving between two of the user's own accounts.
  ///
  /// Written as two rows sharing a transfer id: out of [fromId] and into
  /// [toId]. Each account's balance is then right, while the shared id keeps
  /// the pair out of income and expenditure totals, where it would otherwise
  /// inflate both sides by the same amount.
  static Future<void> transfer({
    required MoneyAccount from,
    required MoneyAccount to,
    required double amount,
    required DateTime date,
    String? note,
  }) async {
    final groupId = const Uuid().v4();
    final label = note?.trim().isNotEmpty == true
        ? note!.trim()
        : 'Transfer: ${from.name} to ${to.name}';

    await UserDataService.addTransaction(
      ExpenseModel(
        id: const Uuid().v4(),
        title: label,
        amount: amount,
        category: transferCategoryName,
        date: date,
        isExpense: true,
        accountId: from.id,
        transferGroupId: groupId,
      ),
    );

    await UserDataService.addTransaction(
      ExpenseModel(
        id: const Uuid().v4(),
        title: label,
        amount: amount,
        category: transferCategoryName,
        date: date,
        isExpense: false,
        accountId: to.id,
        transferGroupId: groupId,
      ),
    );
  }

  /// Reserved category name for the two halves of a transfer.
  static const transferCategoryName = 'Transfer';
}
