import 'dart:io';

import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';

import '../core/models/budget.dart';
import '../core/models/expense_model.dart';
import '../core/utils/money_utils.dart';
import 'budget_service.dart';
import 'user_data_service.dart';

/// Gets the user's records out of the app in a format anything can read.
///
/// The PDF report is a summary written for a person. This is the data itself,
/// so a spreadsheet, another app, or a backup can hold it. Without this the
/// only way out of SmartExpense was to retype everything.
class DataExportService {
  DataExportService._();

  /// RFC 4180: quote the field and double any quote inside it.
  ///
  /// Titles and category names are free text, so a comma, a quote or a
  /// newline in one of them would otherwise shift every later column on that
  /// row into the wrong place.
  static String escapeCsvField(String value) {
    final needsQuoting =
        value.contains(',') ||
        value.contains('"') ||
        value.contains('\n') ||
        value.contains('\r');

    if (!needsQuoting) return value;
    return '"${value.replaceAll('"', '""')}"';
  }

  static String _isoDate(DateTime date) {
    final month = date.month.toString().padLeft(2, '0');
    final day = date.day.toString().padLeft(2, '0');
    return '${date.year}-$month-$day';
  }

  /// Builds the CSV text for [transactions], newest first.
  ///
  /// The amount column is plain rupees with two decimals and no separators or
  /// symbol, so spreadsheets read it as a number rather than as text.
  static String buildTransactionCsv(List<ExpenseModel> transactions) {
    final sorted = List<ExpenseModel>.from(transactions)
      ..sort((a, b) => b.date.compareTo(a.date));

    final buffer = StringBuffer()
      ..writeln('Date,Type,Title,Category,Amount,One-off,Auto-generated');

    for (final transaction in sorted) {
      final row = [
        _isoDate(transaction.date),
        transaction.isExpense ? 'Expense' : 'Income',
        escapeCsvField(transaction.title),
        escapeCsvField(transaction.category),
        (transaction.amountPaisa / 100).toStringAsFixed(2),
        transaction.isWindfall ? 'Yes' : 'No',
        transaction.isAutoGenerated ? 'Yes' : 'No',
      ];
      buffer.writeln(row.join(','));
    }

    return buffer.toString();
  }

  static String buildBudgetCsv(List<Budget> budgets) {
    final buffer = StringBuffer()..writeln('Category,Monthly limit');
    for (final budget in budgets) {
      buffer.writeln(
        '${escapeCsvField(budget.label)},'
        '${(budget.limitPaisa / 100).toStringAsFixed(2)}',
      );
    }
    return buffer.toString();
  }

  /// A short human summary written above the export, so a file found months
  /// later still says what it is.
  static String buildSummary(List<ExpenseModel> transactions) {
    if (transactions.isEmpty) return 'No transactions recorded.';

    final income = transactions
        .where((t) => t.countsAsIncome)
        .fold(0, (sum, t) => sum + t.amountPaisa);
    final expense = transactions
        .where((t) => t.countsAsExpense)
        .fold(0, (sum, t) => sum + t.amountPaisa);

    final dates = transactions.map((t) => t.date).toList()..sort();

    return '${transactions.length} transactions from '
        '${_isoDate(dates.first)} to ${_isoDate(dates.last)}. '
        'Income ${MoneyUtils.formatPaisa(income)}, '
        'spending ${MoneyUtils.formatPaisa(expense)}.';
  }

  static String fileNameFor(DateTime stamp) {
    String two(int value) => value.toString().padLeft(2, '0');
    return 'smartexpense_${stamp.year}${two(stamp.month)}${two(stamp.day)}_'
        '${two(stamp.hour)}${two(stamp.minute)}.csv';
  }

  /// Writes the export to a temporary file and opens the share sheet.
  ///
  /// Returns the number of transactions written, or null if there were none.
  static Future<int?> exportTransactions() async {
    final transactions = await UserDataService.getTransactionsOnce();
    if (transactions.isEmpty) return null;

    final csv = buildTransactionCsv(transactions);
    final directory = await getTemporaryDirectory();
    final file = File(
      '${directory.path}${Platform.pathSeparator}'
      '${fileNameFor(DateTime.now())}',
    );
    await file.writeAsString(csv);

    await Share.shareXFiles(
      [XFile(file.path)],
      subject: 'SmartExpense transactions',
      text: buildSummary(transactions),
    );

    return transactions.length;
  }

  /// Everything the app holds, as one bundle of files.
  static Future<int?> exportEverything() async {
    final transactions = await UserDataService.getTransactionsOnce();
    if (transactions.isEmpty) return null;

    final directory = await getTemporaryDirectory();
    final separator = Platform.pathSeparator;
    final stamp = DateTime.now();

    final files = <XFile>[];

    final transactionsFile = File(
      '${directory.path}$separator${fileNameFor(stamp)}',
    );
    await transactionsFile.writeAsString(buildTransactionCsv(transactions));
    files.add(XFile(transactionsFile.path));

    final budgets = await BudgetService.getOnce();
    if (budgets.isNotEmpty) {
      final budgetFile = File(
        '${directory.path}${separator}smartexpense_budgets.csv',
      );
      await budgetFile.writeAsString(buildBudgetCsv(budgets));
      files.add(XFile(budgetFile.path));
    }

    await Share.shareXFiles(
      files,
      subject: 'SmartExpense data export',
      text: buildSummary(transactions),
    );

    return transactions.length;
  }
}
