import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';

import '../core/models/expense_category.dart';
import '../core/models/expense_model.dart';
import '../core/models/recurring_expense_model.dart';
import '../core/models/user_profile_model.dart';
import 'recurring_expense_service.dart';

class UserDataService {
  UserDataService._();

  static final FirebaseFirestore _firestore = FirebaseFirestore.instance;
  static final FirebaseAuth _auth = FirebaseAuth.instance;

  static Future<void> initialize() async {
    await Future<void>.value();
  }

  static String? get currentUid => _auth.currentUser?.uid;

  static Future<void> saveAuthUserProfileIfMissing() async {
    final user = _auth.currentUser;
    if (user == null) {
      return;
    }

    final snapshot = await _profileDoc().get();
    if (snapshot.exists) {
      return;
    }

    await _profileDoc().set({
      'name': user.displayName ?? '',
      'phoneNumber': '',
      'address': '',
      'email': user.email ?? '',
      'occupation': '',
      'updatedAt': Timestamp.fromDate(DateTime.now()),
      'profileImagePath': user.photoURL,
    });
  }

  static CollectionReference<Map<String, dynamic>> _userCollection() {
    final uid = currentUid;
    if (uid == null || uid.isEmpty) {
      throw StateError('User must be logged in to use Firebase storage.');
    }
    return _firestore.collection('users').doc(uid).collection('data');
  }

  static CollectionReference<ExpenseModel> _transactionCollection() {
    return _userCollection().withConverter<ExpenseModel>(
      fromFirestore: (snapshot, _) => _expenseFromSnapshot(snapshot),
      toFirestore: (expense, _) => {
        'id': expense.id,
        'title': expense.title,
        'amount': expense.amount,
        'category': expense.category,
        'date': Timestamp.fromDate(expense.date),
        'isExpense': expense.isExpense,
        'recurringExpenseId': expense.recurringExpenseId,
        'isAutoGenerated': expense.isAutoGenerated,
        'isWindfall': expense.isWindfall,
      },
    );
  }

  static ExpenseModel _expenseFromSnapshot(
    DocumentSnapshot<Map<String, dynamic>> snapshot,
  ) {
    return expenseFromMap(snapshot.id, snapshot.data() ?? const {});
  }

  /// Rebuilds a transaction from its stored fields.
  ///
  /// The direction is read back exactly as it was written. An earlier version
  /// re-derived it by scanning the title and category for words like "gift",
  /// "business" and "refund", which meant a recorded expense could come back
  /// as income and be added to the wrong side of every total. What the user
  /// chose when saving is the only thing that decides this.
  static ExpenseModel expenseFromMap(String id, Map<String, dynamic> data) {
    return ExpenseModel(
      id: id,
      title: data['title']?.toString() ?? '',
      amount: (data['amount'] as num?)?.toDouble() ?? 0.0,
      category: data['category']?.toString() ?? ExpenseCategory.fallbackName,
      date: (data['date'] as Timestamp?)?.toDate() ?? DateTime.now(),
      isExpense: data['isExpense'] as bool? ?? true,
      recurringExpenseId: data['recurringExpenseId']?.toString(),
      isAutoGenerated: data['isAutoGenerated'] as bool? ?? false,
      isWindfall: data['isWindfall'] as bool? ?? false,
    );
  }

  static DocumentReference<Map<String, dynamic>> _profileDoc() {
    final uid = currentUid;
    if (uid == null || uid.isEmpty) {
      throw StateError('User must be logged in to use Firebase storage.');
    }
    return _firestore.collection('users').doc(uid);
  }

  static Stream<List<ExpenseModel>> transactionsStream() {
    try {
      return _transactionCollection().snapshots().map(
        (snapshot) => snapshot.docs.map((doc) => doc.data()).toList(),
      );
    } catch (_) {
      return Stream.value(const <ExpenseModel>[]);
    }
  }

  static Future<List<ExpenseModel>> getTransactionsOnce() async {
    try {
      final snapshot = await _transactionCollection().get();
      return snapshot.docs.map((doc) => doc.data()).toList();
    } catch (_) {
      return <ExpenseModel>[];
    }
  }

  static Future<List<ExpenseModel>> getRecentTransactions(int limit) async {
    try {
      final snapshot = await _transactionCollection()
          .orderBy('date', descending: true)
          .limit(limit)
          .get();
      return snapshot.docs.map((doc) => doc.data()).toList();
    } catch (_) {
      return <ExpenseModel>[];
    }
  }

  static Future<ExpenseModel?> getTransactionById(String id) async {
    try {
      final snapshot = await _transactionCollection().doc(id).get();
      if (!snapshot.exists) {
        return null;
      }
      return snapshot.data();
    } catch (_) {
      return null;
    }
  }

  static Future<void> updateTransaction(
    String id,
    ExpenseModel transaction,
  ) async {
    try {
      await _transactionCollection().doc(id).set(transaction);
    } catch (e) {
      throw Exception('Unable to update transaction in Firebase: $e');
    }
  }

  static Future<UserProfileModel?> getProfileOnce() async {
    try {
      final snapshot = await _profileDoc().get();
      if (!snapshot.exists || snapshot.data() == null) {
        final user = _auth.currentUser;
        if (user == null) {
          return null;
        }
        return UserProfileModel(
          name: user.displayName ?? '',
          phoneNumber: '',
          address: '',
          email: user.email ?? '',
          occupation: '',
          updatedAt: DateTime.now(),
          profileImagePath: user.photoURL,
        );
      }

      final data = snapshot.data()!;
      return UserProfileModel(
        name: data['name']?.toString() ?? '',
        phoneNumber: data['phoneNumber']?.toString() ?? '',
        address: data['address']?.toString() ?? '',
        email: data['email']?.toString() ?? '',
        occupation: data['occupation']?.toString() ?? '',
        updatedAt:
            (data['updatedAt'] as Timestamp?)?.toDate() ?? DateTime.now(),
        profileImagePath: data['profileImagePath']?.toString(),
      );
    } catch (_) {
      return null;
    }
  }

  static Future<void> addTransaction(ExpenseModel transaction) async {
    try {
      await _transactionCollection().add(transaction);
    } catch (e) {
      throw Exception('Unable to save transaction to Firebase: $e');
    }
  }

  static Future<bool> createTransactionIfMissing(ExpenseModel transaction) async {
    try {
      final doc = _transactionCollection().doc(transaction.id);
      final snapshot = await doc.get();
      if (snapshot.exists) {
        return false;
      }
      await doc.set(transaction);
      return true;
    } catch (e) {
      throw Exception('Unable to save recurring transaction to Firebase: $e');
    }
  }

  static CollectionReference<RecurringExpenseModel> _recurringCollection() {
    final uid = currentUid;
    if (uid == null || uid.isEmpty) {
      throw StateError('User must be logged in to use recurring expenses.');
    }
    return _firestore
        .collection('users')
        .doc(uid)
        .collection('recurringExpenses')
        .withConverter<RecurringExpenseModel>(
          fromFirestore: (snapshot, _) => RecurringExpenseModel.fromJson(
            snapshot.id,
            snapshot.data() ?? const <String, dynamic>{},
          ),
          toFirestore: (expense, _) => {
            ...expense.toJson(),
            'startDate': Timestamp.fromDate(expense.startDate),
            'endDate': expense.endDate == null
                ? null
                : Timestamp.fromDate(expense.endDate!),
            'nextDueDate': Timestamp.fromDate(expense.nextDueDate),
            'lastGeneratedDate': expense.lastGeneratedDate == null
                ? null
                : Timestamp.fromDate(expense.lastGeneratedDate!),
            'createdAt': Timestamp.fromDate(expense.createdAt),
            'updatedAt': Timestamp.fromDate(expense.updatedAt),
          },
        );
  }

  static Stream<List<RecurringExpenseModel>> recurringExpensesStream() {
    try {
      return _recurringCollection()
          .orderBy('nextDueDate')
          .snapshots()
          .map((snapshot) => snapshot.docs.map((doc) => doc.data()).toList());
    } catch (_) {
      return Stream.value(const <RecurringExpenseModel>[]);
    }
  }

  static Future<List<RecurringExpenseModel>> getRecurringExpensesOnce() async {
    try {
      final snapshot = await _recurringCollection().get();
      return snapshot.docs.map((doc) => doc.data()).toList();
    } catch (_) {
      return <RecurringExpenseModel>[];
    }
  }

  static Future<void> saveRecurringExpense(RecurringExpenseModel expense) async {
    try {
      final doc = expense.id.isEmpty
          ? _recurringCollection().doc()
          : _recurringCollection().doc(expense.id);
      await doc.set(expense.copyWith(id: doc.id, updatedAt: DateTime.now()));
    } catch (e) {
      throw Exception('Unable to save recurring expense to Firebase: $e');
    }
  }

  static Future<void> updateRecurringStatus(
    String id,
    RecurringStatus status,
  ) async {
    try {
      await _recurringCollection().doc(id).update({
        'status': status.name,
        'updatedAt': Timestamp.fromDate(DateTime.now()),
      });
    } catch (e) {
      throw Exception('Unable to update recurring expense: $e');
    }
  }

  static Future<void> deleteRecurringExpense(String id) async {
    try {
      await _recurringCollection().doc(id).delete();
    } catch (e) {
      throw Exception('Unable to delete recurring expense: $e');
    }
  }

  static Future<int> runRecurringCatchUp() async {
    final now = DateTime.now();
    final due = RecurringExpenseService.getDueExpenses(
      await getRecurringExpensesOnce(),
      now,
    );
    var generated = 0;

    for (final expense in due) {
      final occurrences = RecurringExpenseService.occurrencesUpTo(
        from: expense.nextDueDate,
        upTo: now,
        frequency: expense.frequency,
        interval: expense.interval,
        endDate: expense.endDate,
      );

      for (final occurrenceDate in occurrences) {
        final created = await createTransactionIfMissing(
          ExpenseModel(
            id: RecurringExpenseService.buildRecurringTransactionId(
              expense.id,
              occurrenceDate,
            ),
            title: expense.title,
            amount: expense.amount,
            category: expense.category,
            date: occurrenceDate,
            isExpense: true,
            recurringExpenseId: expense.id,
            isAutoGenerated: true,
          ),
        );
        if (created) {
          generated++;
        }
      }

      if (occurrences.isNotEmpty) {
        final nextDueDate = RecurringExpenseService.computeNextDueDate(
          occurrences.last,
          expense.frequency,
          expense.interval,
        );
        final ended =
            expense.endDate != null && nextDueDate.isAfter(expense.endDate!);
        await saveRecurringExpense(
          expense.copyWith(
            nextDueDate: nextDueDate,
            lastGeneratedDate: occurrences.last,
            status: ended ? RecurringStatus.ended : RecurringStatus.active,
          ),
        );
      }
    }

    return generated;
  }

  static Future<void> deleteTransaction(String id) async {
    try {
      await _transactionCollection().doc(id).delete();
    } catch (e) {
      throw Exception('Unable to delete transaction from Firebase: $e');
    }
  }

  static Stream<UserProfileModel?> profileStream() {
    try {
      return _profileDoc().snapshots().map((snapshot) {
        if (!snapshot.exists) {
          final user = _auth.currentUser;
          if (user != null) {
            return UserProfileModel(
              name: user.displayName ?? '',
              phoneNumber: '',
              address: '',
              email: user.email ?? '',
              occupation: '',
              updatedAt: DateTime.now(),
              profileImagePath: user.photoURL,
            );
          }
          return null;
        }

        final data = snapshot.data();
        if (data == null) {
          final user = _auth.currentUser;
          if (user != null) {
            return UserProfileModel(
              name: user.displayName ?? '',
              phoneNumber: '',
              address: '',
              email: user.email ?? '',
              occupation: '',
              updatedAt: DateTime.now(),
              profileImagePath: user.photoURL,
            );
          }
          return null;
        }

        return UserProfileModel(
          name: data['name']?.toString() ?? '',
          phoneNumber: data['phoneNumber']?.toString() ?? '',
          address: data['address']?.toString() ?? '',
          email: data['email']?.toString() ?? '',
          occupation: data['occupation']?.toString() ?? '',
          updatedAt:
              (data['updatedAt'] as Timestamp?)?.toDate() ?? DateTime.now(),
          profileImagePath: data['profileImagePath']?.toString(),
        );
      });
    } catch (_) {
      return Stream.value(null);
    }
  }

  static Future<void> saveProfile(UserProfileModel profile) async {
    try {
      await _profileDoc().set({
        'name': profile.name,
        'phoneNumber': profile.phoneNumber,
        'address': profile.address,
        'email': profile.email,
        'occupation': profile.occupation,
        'updatedAt': Timestamp.fromDate(profile.updatedAt),
        'profileImagePath': profile.profileImagePath,
      }, SetOptions(merge: true));
    } catch (e) {
      throw Exception('Unable to save profile to Firebase: $e');
    }
  }
}
