import '../utils/money_utils.dart';

class ExpenseModel {
  final String id;
  final String title;
  final double amount;
  final String category; // e.g., 'Food', 'Travel', 'Shopping'
  final DateTime date;
  final bool isExpense; // true for expense, false for income
  final String? recurringExpenseId;
  final bool isAutoGenerated;

  /// A one-off amount that is not part of the usual pattern — an asset sale,
  /// a windfall, a large reimbursement.
  ///
  /// It still counts towards the balance, but is left out of savings rate and
  /// per-period averages. Without this a single land sale made the savings
  /// rate read 99% and skewed every piece of advice built on it.
  final bool isWindfall;

  ExpenseModel({
    required this.id,
    required this.title,
    required this.amount,
    required this.category,
    required this.date,
    required this.isExpense,
    this.recurringExpenseId,
    this.isAutoGenerated = false,
    this.isWindfall = false,
  });

  int get amountPaisa => MoneyUtils.amountToPaisa(amount);

  /// Counts towards rates and averages that describe a typical period.
  bool get isRegular => !isWindfall;

  ExpenseModel copyWith({
    String? title,
    double? amount,
    String? category,
    DateTime? date,
    bool? isExpense,
    bool? isWindfall,
  }) {
    return ExpenseModel(
      id: id,
      title: title ?? this.title,
      amount: amount ?? this.amount,
      category: category ?? this.category,
      date: date ?? this.date,
      isExpense: isExpense ?? this.isExpense,
      recurringExpenseId: recurringExpenseId,
      isAutoGenerated: isAutoGenerated,
      isWindfall: isWindfall ?? this.isWindfall,
    );
  }
}
